force-app/main/default/objects/Account/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <inlineHelpText>The IBAN consists of up to 34 alphanumeric characters, as follows:
country code using ISO 3166-1 alpha-2 – two letters,
check digits – two digits, and
Basic Bank Account Number (BBAN) – up to 30 alphanumeric characters that are country-specific.</inlineHelpText>
    <label>IBAN</label>
    <length>43</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IBAN_Status__c.field-meta.xml
<CustomField>
    <fullName>IBAN_Status__c</fullName>
    <label>IBAN Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateAccountIban.cls
public class UpdateAccountIban implements Queueable, Database.AllowsCallouts {
	@testVisible
    private static Boolean throwError = false;
    @testVisible
    private static Boolean circuitBreakerThrown = false;
    @testVisible
    private List<Account> accounts;

    public UpdateAccountIban(List<Account> triggerNewRecords) {
        this.accounts = triggerNewRecords;
    }

    public class UpdateAccountIbanException extends Exception {
    }

    public void execute(QueueableContext context) {

        List<Account> accountsToValidation = [
            SELECT Id, Name, IBAN__c, IBAN_Status__c
            FROM Account
            WHERE Id IN :accounts
        ];

        if (!throwError) {
            for (Account account : accountsToValidation) {
                String ibanNumber = account.IBAN__c;
                account.IBAN_Status__c = IBANValidation.ibanValidate(ibanNumber);
            }
        }
        if (Test.isRunningTest() && throwError) {
            for (Account account : accountsToValidation) {
                account.Name = '';
            }
        }

        try {
	        update  accountsToValidation;
        } catch (DmlException dmle) {
            System.debug(
                LoggingLevel.INFO,
                'real life use cases should do something more than just logging the error: ' +
                dmle.getMessage()
            );
            if (Test.isRunningTest()) {
                UpdateAccountIban.circuitBreakerThrown = true;
            }
        }
    }
}