force-app/main/default/objects/Account/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <inlineHelpText>The IBAN consists of up to 34 alphanumeric characters, as follows:
country code using ISO 3166-1 alpha-2 – two letters,
check digits – two digits, and
Basic Bank Account Number (BBAN) – up to 30 alphanumeric characters that are country-specific.</inlineHelpText>
    <label>IBAN</label>
    <length>43</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IBAN_Status__c.field-meta.xml
<CustomField>
    <fullName>IBAN_Status__c</fullName>
    <label>IBAN Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountIbanTriggerHandler.cls
public class AccountIbanTriggerHandler {

    public void ibanValidate(List<Account> accountsToValidate){
        UpdateAccountIban updateJob = new UpdateAccountIban(accountsToValidate);

       System.enqueueJob(updateJob);

    }

}





/*
// enqueue the job for processing
ID jobID = System.enqueueJob(updateJob);
List<AsyncApexJob> async = [
            SELECT Id, Status, NumberOfErrors
            FROM AsyncApexJob
            WHERE Id = :jobId
        ];
        System.debug('async ' + async);
*/

// String ibanNum = 'DE 89370400440532013000';
// IBANValidation.ibanValidate('DE 89370400440532013000');

// Account acct1 = new Account(Name='Test Account1', IBAN__c = 'DE 89370400440532013000');
//Account acct2 = new Account(Name='Test Account2', IBAN__c = 'DE8937040044053201300');
//List <Account> a = new List <Account> {acct1, acct2};
//insert a;
/*
Set<Id> ibanIds = new Set<Id>();
List<Account> accountsToUpdate = new List<Account>();
List<String> accountIbanNumbers = new List <String>();

public void beforeIbanInsert(List<Account> triggerNew)
{
for(Account account : triggerNew){
//account.IBAN_Status__c = 'In progress';
}
}
*/